name: Build and Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/blog

    steps:
      - name: Generate timestamp and git SHA tag
        id: vars
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d')
          GIT_SHA=$(git rev-parse --short HEAD)
          FULL_TAG="${TIMESTAMP}-g${GIT_SHA}"
          echo "FULL_TAG=$FULL_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.FULL_TAG }}

      - name: Output deployment info
        run: |
          echo "✅ Deployment completed successfully!"
          echo "🐳 Pushed Docker images:"
          echo "   - ${{ env.IMAGE_NAME }}:latest"
          echo "   - ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.FULL_TAG }}"
          echo "🚀 VPS deployment triggered"
          echo "⏰ Watchtower will automatically update the running container"
